name: match-labels
description: "Match labels from pull request and return matched labels"
inputs:
  default_label:
    description: "Default label"
    required: false
  match_labels:
    description: "Match labels"
    required: true
runs:
  using: node16
  main: dist/main.js
